# Simple Agent
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_executor.sh
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_fewshot_expert_executor.sh
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_fewshot_nonexpert_executor.sh
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_rag_tag_executor.sh 

# Agentinc
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_agentic_executor.sh
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_agentic_fewshot_expert_executor.sh
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_agentic_fewshot_nonexpert_executor.sh
bash scripts_cleaned/task_mult/deepseek-chat/run_benchmark_agentic_rag_tag_executor.sh 